### ISSUE TITLE
Did U just assume my operating system?

### ISSUE THREAD

**Issue by NitroNils** [ReceiptManager/receipt-parser-server#11]
`apt-get` is very specific to Debian based OS'. I'm sure most people get that, but why not say something like _Use your package manager to install…_ to not offend people (like me ^^).

I'm happy to see this program and hope it will work on a FreeBSD based OS too!

**Comment by monolidth** [comment]
You right. The Debian package manager should not be the default package manager. I fixed this issue at https://github.com/ReceiptManager/Server/commit/0ba3c2ce9313398831e4cf38eadf8e7829735ff6.

I personally do not even use Debian. Hope, this issue is resolved. Thanks for covering it.

Regards,
William
